import type { CSSProperties } from 'react';
import type { SelectTheme, SelectThemeInput } from './Select.theme.types';
import { selectThemes } from './defaultThemes';

export function resolveTheme(theme?: SelectThemeInput): SelectTheme {
  if (!theme) return selectThemes.light;
  if (typeof theme === 'string') return selectThemes[theme];
  return theme;
}

/** Convierte el tema en CSS variables para el root del Select */
export function themeToStyle(theme: SelectTheme): CSSProperties {
  const v = theme.variants;
  return {
    '--select-font-size': theme.fontSize,
    '--select-radius': theme.borderRadius,
    '--select-transition': theme.transition,
    '--select-shadow': theme.shadow,
    '--select-dropdown-shadow': theme.dropdownShadow,
    '--select-dropdown-border': theme.dropdownBorder,
    '--select-dropdown-bg': theme.dropdownBg,
    '--select-helper-color': theme.helperTextColor,
    '--select-error-color': theme.errorTextColor,
    '--select-label-color': theme.labelColor,
    /* Primary */
    '--select-primary-bg': v.primary.background,
    '--select-primary-text': v.primary.text,
    '--select-primary-border': v.primary.border,
    '--select-primary-placeholder': v.primary.placeholderColor,
    '--select-primary-icon': v.primary.iconColor,
    '--select-primary-hover-bg': v.primary.hoverBackground,
    '--select-primary-hover-border': v.primary.hoverBorder,
    '--select-primary-focus-bg': v.primary.focusBackground,
    '--select-primary-focus-border': v.primary.focusBorder,
    '--select-primary-focus-ring': v.primary.focusRing,
    '--select-primary-disabled-bg': v.primary.disabledBackground,
    '--select-primary-disabled-text': v.primary.disabledText,
    '--select-primary-disabled-border': v.primary.disabledBorder,
    '--select-primary-error-border': v.primary.errorBorder,
    '--select-primary-error-focus-ring': v.primary.errorFocusRing,
    '--select-primary-option-bg': v.primary.optionBackground,
    '--select-primary-option-text': v.primary.optionText,
    '--select-primary-option-hover-bg': v.primary.optionHoverBackground,
    '--select-primary-option-hover-text': v.primary.optionHoverText,
    '--select-primary-option-selected-bg': v.primary.optionSelectedBackground,
    '--select-primary-option-selected-text': v.primary.optionSelectedText,
    '--select-primary-option-disabled-text': v.primary.optionDisabledText,
    /* Secondary */
    '--select-secondary-bg': v.secondary.background,
    '--select-secondary-text': v.secondary.text,
    '--select-secondary-border': v.secondary.border,
    '--select-secondary-placeholder': v.secondary.placeholderColor,
    '--select-secondary-icon': v.secondary.iconColor,
    '--select-secondary-hover-bg': v.secondary.hoverBackground,
    '--select-secondary-hover-border': v.secondary.hoverBorder,
    '--select-secondary-focus-bg': v.secondary.focusBackground,
    '--select-secondary-focus-border': v.secondary.focusBorder,
    '--select-secondary-focus-ring': v.secondary.focusRing,
    '--select-secondary-disabled-bg': v.secondary.disabledBackground,
    '--select-secondary-disabled-text': v.secondary.disabledText,
    '--select-secondary-disabled-border': v.secondary.disabledBorder,
    '--select-secondary-error-border': v.secondary.errorBorder,
    '--select-secondary-error-focus-ring': v.secondary.errorFocusRing,
    '--select-secondary-option-bg': v.secondary.optionBackground,
    '--select-secondary-option-text': v.secondary.optionText,
    '--select-secondary-option-hover-bg': v.secondary.optionHoverBackground,
    '--select-secondary-option-hover-text': v.secondary.optionHoverText,
    '--select-secondary-option-selected-bg': v.secondary.optionSelectedBackground,
    '--select-secondary-option-selected-text': v.secondary.optionSelectedText,
    '--select-secondary-option-disabled-text': v.secondary.optionDisabledText,
    /* Outline */
    '--select-outline-bg': v.outline.background,
    '--select-outline-text': v.outline.text,
    '--select-outline-border': v.outline.border,
    '--select-outline-placeholder': v.outline.placeholderColor,
    '--select-outline-icon': v.outline.iconColor,
    '--select-outline-hover-bg': v.outline.hoverBackground,
    '--select-outline-hover-border': v.outline.hoverBorder,
    '--select-outline-focus-bg': v.outline.focusBackground,
    '--select-outline-focus-border': v.outline.focusBorder,
    '--select-outline-focus-ring': v.outline.focusRing,
    '--select-outline-disabled-bg': v.outline.disabledBackground,
    '--select-outline-disabled-text': v.outline.disabledText,
    '--select-outline-disabled-border': v.outline.disabledBorder,
    '--select-outline-error-border': v.outline.errorBorder,
    '--select-outline-error-focus-ring': v.outline.errorFocusRing,
    '--select-outline-option-bg': v.outline.optionBackground,
    '--select-outline-option-text': v.outline.optionText,
    '--select-outline-option-hover-bg': v.outline.optionHoverBackground,
    '--select-outline-option-hover-text': v.outline.optionHoverText,
    '--select-outline-option-selected-bg': v.outline.optionSelectedBackground,
    '--select-outline-option-selected-text': v.outline.optionSelectedText,
    '--select-outline-option-disabled-text': v.outline.optionDisabledText,
    /* Ghost */
    '--select-ghost-bg': v.ghost.background,
    '--select-ghost-text': v.ghost.text,
    '--select-ghost-border': v.ghost.border,
    '--select-ghost-placeholder': v.ghost.placeholderColor,
    '--select-ghost-icon': v.ghost.iconColor,
    '--select-ghost-hover-bg': v.ghost.hoverBackground,
    '--select-ghost-hover-border': v.ghost.hoverBorder,
    '--select-ghost-focus-bg': v.ghost.focusBackground,
    '--select-ghost-focus-border': v.ghost.focusBorder,
    '--select-ghost-focus-ring': v.ghost.focusRing,
    '--select-ghost-disabled-bg': v.ghost.disabledBackground,
    '--select-ghost-disabled-text': v.ghost.disabledText,
    '--select-ghost-disabled-border': v.ghost.disabledBorder,
    '--select-ghost-error-border': v.ghost.errorBorder,
    '--select-ghost-error-focus-ring': v.ghost.errorFocusRing,
    '--select-ghost-option-bg': v.ghost.optionBackground,
    '--select-ghost-option-text': v.ghost.optionText,
    '--select-ghost-option-hover-bg': v.ghost.optionHoverBackground,
    '--select-ghost-option-hover-text': v.ghost.optionHoverText,
    '--select-ghost-option-selected-bg': v.ghost.optionSelectedBackground,
    '--select-ghost-option-selected-text': v.ghost.optionSelectedText,
    '--select-ghost-option-disabled-text': v.ghost.optionDisabledText,
  } as CSSProperties;
}
