import type { ButtonTheme, ButtonThemePreset } from './Button.theme.types';

export const buttonThemes: Record<ButtonThemePreset, ButtonTheme> = {
  dark: {
    fontSize: '0.875rem',
    borderRadius: '0.5rem',
    transition: 'all 0.15s ease',
    shadow: '0 1px 2px rgba(0, 0, 0, 0.3)',
    hoverShadow: '0 4px 12px rgba(0, 0, 0, 0.4)',
    variants: {
      primary: {
        background: '#6366f1',
        text: '#ffffff',
        border: '#6366f1',
        hoverBackground: '#818cf8',
        hoverBorder: '#818cf8',
        activeBackground: '#4f46e5',
        activeBorder: '#4f46e5',
        focusRing: 'rgba(99, 102, 241, 0.5)',
        disabledBackground: '#374151',
        disabledText: '#6b7280',
        disabledBorder: '#374151',
        spinnerColor: '#ffffff',
      },
      secondary: {
        background: '#374151',
        text: '#e5e7eb',
        border: '#374151',
        hoverBackground: '#4b5563',
        hoverBorder: '#4b5563',
        activeBackground: '#1f2937',
        activeBorder: '#1f2937',
        focusRing: 'rgba(107, 114, 128, 0.5)',
        disabledBackground: '#1f2937',
        disabledText: '#6b7280',
        disabledBorder: '#1f2937',
        spinnerColor: '#e5e7eb',
      },
      outline: {
        background: 'transparent',
        text: '#e5e7eb',
        border: '#4b5563',
        hoverBackground: 'rgba(255, 255, 255, 0.05)',
        hoverBorder: '#6b7280',
        activeBackground: 'rgba(255, 255, 255, 0.08)',
        activeBorder: '#9ca3af',
        focusRing: 'rgba(156, 163, 175, 0.5)',
        disabledBackground: 'transparent',
        disabledText: '#4b5563',
        disabledBorder: '#374151',
        spinnerColor: '#e5e7eb',
      },
      ghost: {
        background: 'transparent',
        text: '#e5e7eb',
        border: 'transparent',
        hoverBackground: 'rgba(255, 255, 255, 0.05)',
        hoverBorder: 'transparent',
        activeBackground: 'rgba(255, 255, 255, 0.08)',
        activeBorder: 'transparent',
        focusRing: 'rgba(156, 163, 175, 0.5)',
        disabledBackground: 'transparent',
        disabledText: '#4b5563',
        disabledBorder: 'transparent',
        spinnerColor: '#e5e7eb',
      },
      danger: {
        background: '#dc2626',
        text: '#ffffff',
        border: '#dc2626',
        hoverBackground: '#ef4444',
        hoverBorder: '#ef4444',
        activeBackground: '#b91c1c',
        activeBorder: '#b91c1c',
        focusRing: 'rgba(220, 38, 38, 0.5)',
        disabledBackground: '#374151',
        disabledText: '#6b7280',
        disabledBorder: '#374151',
        spinnerColor: '#ffffff',
      },
    },
  },
  light: {
    fontSize: '0.875rem',
    borderRadius: '0.5rem',
    transition: 'all 0.15s ease',
    shadow: '0 1px 2px rgba(0, 0, 0, 0.06)',
    hoverShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    variants: {
      primary: {
        background: '#4f46e5',
        text: '#ffffff',
        border: '#4f46e5',
        hoverBackground: '#6366f1',
        hoverBorder: '#6366f1',
        activeBackground: '#4338ca',
        activeBorder: '#4338ca',
        focusRing: 'rgba(79, 70, 229, 0.4)',
        disabledBackground: '#e5e7eb',
        disabledText: '#9ca3af',
        disabledBorder: '#e5e7eb',
        spinnerColor: '#ffffff',
      },
      secondary: {
        background: '#f3f4f6',
        text: '#1f2937',
        border: '#f3f4f6',
        hoverBackground: '#e5e7eb',
        hoverBorder: '#e5e7eb',
        activeBackground: '#d1d5db',
        activeBorder: '#d1d5db',
        focusRing: 'rgba(156, 163, 175, 0.5)',
        disabledBackground: '#f9fafb',
        disabledText: '#d1d5db',
        disabledBorder: '#f9fafb',
        spinnerColor: '#1f2937',
      },
      outline: {
        background: 'transparent',
        text: '#374151',
        border: '#d1d5db',
        hoverBackground: 'rgba(0, 0, 0, 0.02)',
        hoverBorder: '#9ca3af',
        activeBackground: 'rgba(0, 0, 0, 0.04)',
        activeBorder: '#6b7280',
        focusRing: 'rgba(156, 163, 175, 0.5)',
        disabledBackground: 'transparent',
        disabledText: '#d1d5db',
        disabledBorder: '#e5e7eb',
        spinnerColor: '#374151',
      },
      ghost: {
        background: 'transparent',
        text: '#374151',
        border: 'transparent',
        hoverBackground: 'rgba(0, 0, 0, 0.04)',
        hoverBorder: 'transparent',
        activeBackground: 'rgba(0, 0, 0, 0.06)',
        activeBorder: 'transparent',
        focusRing: 'rgba(156, 163, 175, 0.5)',
        disabledBackground: 'transparent',
        disabledText: '#d1d5db',
        disabledBorder: 'transparent',
        spinnerColor: '#374151',
      },
      danger: {
        background: '#dc2626',
        text: '#ffffff',
        border: '#dc2626',
        hoverBackground: '#ef4444',
        hoverBorder: '#ef4444',
        activeBackground: '#b91c1c',
        activeBorder: '#b91c1c',
        focusRing: 'rgba(220, 38, 38, 0.4)',
        disabledBackground: '#fecaca',
        disabledText: '#fca5a5',
        disabledBorder: '#fecaca',
        spinnerColor: '#ffffff',
      },
    },
  },

  'modern-dark': {
      "fontSize": "0.875rem",
      "borderRadius": "0.5rem",
      "transition": "all 0.15s ease",
      "shadow": "0 1px 2px rgba(0, 0, 0, 0.3)",
      "hoverShadow": "0 4px 12px rgba(0, 0, 0, 0.4)",
      "variants": {
        "primary": {
          "background": "#10b981",
          "text": "#ffffff",
          "border": "#10b981",
          "hoverBackground": "#34d399",
          "hoverBorder": "#34d399",
          "activeBackground": "#059669",
          "activeBorder": "#059669",
          "focusRing": "rgba(16, 185, 129, 0.5)",
          "disabledBackground": "#374151",
          "disabledText": "#6b7280",
          "disabledBorder": "#374151",
          "spinnerColor": "#ffffff",
        },
        "secondary": {
          "background": "#374151",
          "text": "#e5e7eb",
          "border": "#374151",
          "hoverBackground": "#4b5563",
          "hoverBorder": "#4b5563",
          "activeBackground": "#1f2937",
          "activeBorder": "#1f2937",
          "focusRing": "rgba(107, 114, 128, 0.5)",
          "disabledBackground": "#1f2937",
          "disabledText": "#6b7280",
          "disabledBorder": "#1f2937",
          "spinnerColor": "#e5e7eb",
        },
        "outline": {
          "background": "transparent",
          "text": "#e5e7eb",
          "border": "#4b5563",
          "hoverBackground": "rgba(255, 255, 255, 0.05)",
          "hoverBorder": "#6b7280",
          "activeBackground": "rgba(255, 255, 255, 0.08)",
          "activeBorder": "#9ca3af",
          "focusRing": "rgba(156, 163, 175, 0.5)",
          "disabledBackground": "transparent",
          "disabledText": "#4b5563",
          "disabledBorder": "#374151",
          "spinnerColor": "#e5e7eb",
        },
        "ghost": {
          "background": "transparent",
          "text": "#e5e7eb",
          "border": "transparent",
          "hoverBackground": "rgba(255, 255, 255, 0.05)",
          "hoverBorder": "transparent",
          "activeBackground": "rgba(255, 255, 255, 0.08)",
          "activeBorder": "transparent",
          "focusRing": "rgba(156, 163, 175, 0.5)",
          "disabledBackground": "transparent",
          "disabledText": "#4b5563",
          "disabledBorder": "transparent",
          "spinnerColor": "#e5e7eb",
        },
        "danger": {
          "background": "#dc2626",
          "text": "#ffffff",
          "border": "#dc2626",
          "hoverBackground": "#ef4444",
          "hoverBorder": "#ef4444",
          "activeBackground": "#b91c1c",
          "activeBorder": "#b91c1c",
          "focusRing": "rgba(220, 38, 38, 0.5)",
          "disabledBackground": "#374151",
          "disabledText": "#6b7280",
          "disabledBorder": "#374151",
          "spinnerColor": "#ffffff",
        },
      },
    },
  'modern-light': {
      "fontSize": "0.875rem",
      "borderRadius": "0.5rem",
      "transition": "all 0.15s ease",
      "shadow": "0 1px 2px rgba(0, 0, 0, 0.06)",
      "hoverShadow": "0 4px 12px rgba(0, 0, 0, 0.1)",
      "variants": {
        "primary": {
          "background": "#059669",
          "text": "#ffffff",
          "border": "#059669",
          "hoverBackground": "#10b981",
          "hoverBorder": "#10b981",
          "activeBackground": "#047857",
          "activeBorder": "#047857",
          "focusRing": "rgba(5, 150, 105, 0.4)",
          "disabledBackground": "#e5e7eb",
          "disabledText": "#9ca3af",
          "disabledBorder": "#e5e7eb",
          "spinnerColor": "#ffffff",
        },
        "secondary": {
          "background": "#f3f4f6",
          "text": "#1f2937",
          "border": "#f3f4f6",
          "hoverBackground": "#e5e7eb",
          "hoverBorder": "#e5e7eb",
          "activeBackground": "#d1d5db",
          "activeBorder": "#d1d5db",
          "focusRing": "rgba(156, 163, 175, 0.5)",
          "disabledBackground": "#f9fafb",
          "disabledText": "#d1d5db",
          "disabledBorder": "#f9fafb",
          "spinnerColor": "#1f2937",
        },
        "outline": {
          "background": "transparent",
          "text": "#374151",
          "border": "#d1d5db",
          "hoverBackground": "rgba(0, 0, 0, 0.02)",
          "hoverBorder": "#9ca3af",
          "activeBackground": "rgba(0, 0, 0, 0.04)",
          "activeBorder": "#6b7280",
          "focusRing": "rgba(156, 163, 175, 0.5)",
          "disabledBackground": "transparent",
          "disabledText": "#d1d5db",
          "disabledBorder": "#e5e7eb",
          "spinnerColor": "#374151",
        },
        "ghost": {
          "background": "transparent",
          "text": "#374151",
          "border": "transparent",
          "hoverBackground": "rgba(0, 0, 0, 0.04)",
          "hoverBorder": "transparent",
          "activeBackground": "rgba(0, 0, 0, 0.06)",
          "activeBorder": "transparent",
          "focusRing": "rgba(156, 163, 175, 0.5)",
          "disabledBackground": "transparent",
          "disabledText": "#d1d5db",
          "disabledBorder": "transparent",
          "spinnerColor": "#374151",
        },
        "danger": {
          "background": "#dc2626",
          "text": "#ffffff",
          "border": "#dc2626",
          "hoverBackground": "#ef4444",
          "hoverBorder": "#ef4444",
          "activeBackground": "#b91c1c",
          "activeBorder": "#b91c1c",
          "focusRing": "rgba(220, 38, 38, 0.4)",
          "disabledBackground": "#fecaca",
          "disabledText": "#fca5a5",
          "disabledBorder": "#fecaca",
          "spinnerColor": "#ffffff",
        },
      },
    },
  'enterprise-dark': {
      "fontSize": "0.875rem",
      "borderRadius": "0.5rem",
      "transition": "all 0.15s ease",
      "shadow": "0 1px 2px rgba(0, 0, 0, 0.3)",
      "hoverShadow": "0 4px 12px rgba(0, 0, 0, 0.4)",
      "variants": {
        "primary": {
          "background": "#3b82f6",
          "text": "#ffffff",
          "border": "#3b82f6",
          "hoverBackground": "#60a5fa",
          "hoverBorder": "#60a5fa",
          "activeBackground": "#2563eb",
          "activeBorder": "#2563eb",
          "focusRing": "rgba(59, 130, 246, 0.5)",
          "disabledBackground": "#374151",
          "disabledText": "#6b7280",
          "disabledBorder": "#374151",
          "spinnerColor": "#ffffff",
        },
        "secondary": {
          "background": "#374151",
          "text": "#e5e7eb",
          "border": "#374151",
          "hoverBackground": "#4b5563",
          "hoverBorder": "#4b5563",
          "activeBackground": "#1f2937",
          "activeBorder": "#1f2937",
          "focusRing": "rgba(107, 114, 128, 0.5)",
          "disabledBackground": "#1f2937",
          "disabledText": "#6b7280",
          "disabledBorder": "#1f2937",
          "spinnerColor": "#e5e7eb",
        },
        "outline": {
          "background": "transparent",
          "text": "#e5e7eb",
          "border": "#4b5563",
          "hoverBackground": "rgba(255, 255, 255, 0.05)",
          "hoverBorder": "#6b7280",
          "activeBackground": "rgba(255, 255, 255, 0.08)",
          "activeBorder": "#9ca3af",
          "focusRing": "rgba(156, 163, 175, 0.5)",
          "disabledBackground": "transparent",
          "disabledText": "#4b5563",
          "disabledBorder": "#374151",
          "spinnerColor": "#e5e7eb",
        },
        "ghost": {
          "background": "transparent",
          "text": "#e5e7eb",
          "border": "transparent",
          "hoverBackground": "rgba(255, 255, 255, 0.05)",
          "hoverBorder": "transparent",
          "activeBackground": "rgba(255, 255, 255, 0.08)",
          "activeBorder": "transparent",
          "focusRing": "rgba(156, 163, 175, 0.5)",
          "disabledBackground": "transparent",
          "disabledText": "#4b5563",
          "disabledBorder": "transparent",
          "spinnerColor": "#e5e7eb",
        },
        "danger": {
          "background": "#dc2626",
          "text": "#ffffff",
          "border": "#dc2626",
          "hoverBackground": "#ef4444",
          "hoverBorder": "#ef4444",
          "activeBackground": "#b91c1c",
          "activeBorder": "#b91c1c",
          "focusRing": "rgba(220, 38, 38, 0.5)",
          "disabledBackground": "#374151",
          "disabledText": "#6b7280",
          "disabledBorder": "#374151",
          "spinnerColor": "#ffffff",
        },
      },
    },
  'enterprise-light': {
      "fontSize": "0.875rem",
      "borderRadius": "0.5rem",
      "transition": "all 0.15s ease",
      "shadow": "0 1px 2px rgba(0, 0, 0, 0.06)",
      "hoverShadow": "0 4px 12px rgba(0, 0, 0, 0.1)",
      "variants": {
        "primary": {
          "background": "#2563eb",
          "text": "#ffffff",
          "border": "#2563eb",
          "hoverBackground": "#3b82f6",
          "hoverBorder": "#3b82f6",
          "activeBackground": "#1d4ed8",
          "activeBorder": "#1d4ed8",
          "focusRing": "rgba(37, 99, 235, 0.4)",
          "disabledBackground": "#e5e7eb",
          "disabledText": "#9ca3af",
          "disabledBorder": "#e5e7eb",
          "spinnerColor": "#ffffff",
        },
        "secondary": {
          "background": "#f3f4f6",
          "text": "#1f2937",
          "border": "#f3f4f6",
          "hoverBackground": "#e5e7eb",
          "hoverBorder": "#e5e7eb",
          "activeBackground": "#d1d5db",
          "activeBorder": "#d1d5db",
          "focusRing": "rgba(156, 163, 175, 0.5)",
          "disabledBackground": "#f9fafb",
          "disabledText": "#d1d5db",
          "disabledBorder": "#f9fafb",
          "spinnerColor": "#1f2937",
        },
        "outline": {
          "background": "transparent",
          "text": "#374151",
          "border": "#d1d5db",
          "hoverBackground": "rgba(0, 0, 0, 0.02)",
          "hoverBorder": "#9ca3af",
          "activeBackground": "rgba(0, 0, 0, 0.04)",
          "activeBorder": "#6b7280",
          "focusRing": "rgba(156, 163, 175, 0.5)",
          "disabledBackground": "transparent",
          "disabledText": "#d1d5db",
          "disabledBorder": "#e5e7eb",
          "spinnerColor": "#374151",
        },
        "ghost": {
          "background": "transparent",
          "text": "#374151",
          "border": "transparent",
          "hoverBackground": "rgba(0, 0, 0, 0.04)",
          "hoverBorder": "transparent",
          "activeBackground": "rgba(0, 0, 0, 0.06)",
          "activeBorder": "transparent",
          "focusRing": "rgba(156, 163, 175, 0.5)",
          "disabledBackground": "transparent",
          "disabledText": "#d1d5db",
          "disabledBorder": "transparent",
          "spinnerColor": "#374151",
        },
        "danger": {
          "background": "#dc2626",
          "text": "#ffffff",
          "border": "#dc2626",
          "hoverBackground": "#ef4444",
          "hoverBorder": "#ef4444",
          "activeBackground": "#b91c1c",
          "activeBorder": "#b91c1c",
          "focusRing": "rgba(220, 38, 38, 0.4)",
          "disabledBackground": "#fecaca",
          "disabledText": "#fca5a5",
          "disabledBorder": "#fecaca",
          "spinnerColor": "#ffffff",
        },
      },
    },
};