import type { ComponentMeta } from '@/demo/playground/types';
import type { FileBoxProps } from '@/components/FileBox';

export const fileBoxMeta: ComponentMeta<FileBoxProps> = {
  name: 'FileBox',
  description:
    'Selector de archivos con modo campo o dropzone, validación de tipo/tamaño, múltiple, clearable y el mismo sistema visual de TextBox.',
  sourcePath: 'src/components/FileBox/FileBox.tsx',
  fullWidthPreview: true,
  defaults: {
    placeholder: 'Ningún archivo seleccionado',
    buttonLabel: 'Elegir archivo',
    variant: 'primary',
    size: 'md',
    labelPosition: 'top',
    displayMode: 'field',
    multiple: false,
    showClearButton: true,
    disabled: false,
    error: false,
    fullWidth: true,
  },
  sections: [
    {
      title: 'Contenido',
      props: [
        {
          name: 'label',
          type: 'string',
          defaultValue: undefined,
          description: 'Etiqueta del campo.',
          control: 'text',
        },
        {
          name: 'placeholder',
          type: 'string',
          defaultValue: 'Ningún archivo seleccionado',
          description: 'Texto cuando no hay archivos (modo field).',
          control: 'text',
        },
        {
          name: 'buttonLabel',
          type: 'string',
          defaultValue: 'Elegir archivo',
          description: 'Texto del botón de selección (modo field).',
          control: 'text',
        },
        {
          name: 'accept',
          type: 'string',
          defaultValue: undefined,
          description: 'Filtro accept nativo. Ej: "image/*,.pdf".',
          control: 'text',
        },
        {
          name: 'multiple',
          type: 'boolean',
          defaultValue: false,
          description: 'Permite seleccionar varios archivos.',
          control: 'boolean',
        },
        {
          name: 'maxSize',
          type: 'number',
          defaultValue: undefined,
          description: 'Tamaño máximo por archivo en bytes.',
          control: 'number',
        },
        {
          name: 'maxFiles',
          type: 'number',
          defaultValue: undefined,
          description: 'Cantidad máxima de archivos (con multiple).',
          control: 'number',
        },
      ],
    },
    {
      title: 'Apariencia',
      props: [
        {
          name: 'displayMode',
          type: 'FileBoxDisplayMode',
          defaultValue: 'field',
          description: "'field': campo compacto. 'dropzone': área de arrastre.",
          control: 'select',
          options: [
            { label: 'Field', value: 'field' },
            { label: 'Dropzone', value: 'dropzone' },
          ],
        },
        {
          name: 'variant',
          type: 'FileBoxVariant',
          defaultValue: 'primary',
          description: 'Variante visual del campo.',
          control: 'select',
          options: [
            { label: 'Primary', value: 'primary' },
            { label: 'Secondary', value: 'secondary' },
            { label: 'Outline', value: 'outline' },
            { label: 'Ghost', value: 'ghost' },
          ],
        },
        {
          name: 'size',
          type: 'FileBoxSize',
          defaultValue: 'md',
          description: 'Tamaño del campo.',
          control: 'select',
          options: [
            { label: 'Small', value: 'sm' },
            { label: 'Medium', value: 'md' },
            { label: 'Large', value: 'lg' },
          ],
        },
        {
          name: 'labelPosition',
          type: 'FileBoxLabelPosition',
          defaultValue: 'top',
          description: "'top' o 'left' (floating/outlined se muestran como top).",
          control: 'select',
          options: [
            { label: 'Top', value: 'top' },
            { label: 'Left', value: 'left' },
            { label: 'Outlined', value: 'outlined' },
            { label: 'Floating', value: 'floating' },
          ],
        },
        {
          name: 'fullWidth',
          type: 'boolean',
          defaultValue: true,
          description: 'Ocupa todo el ancho disponible.',
          control: 'boolean',
        },
        {
          name: 'width',
          type: 'string | number',
          defaultValue: undefined,
          description: 'Ancho fijo. Prevalece sobre fullWidth.',
          control: 'text',
        },
      ],
    },
    {
      title: 'Estado',
      props: [
        {
          name: 'showClearButton',
          type: 'boolean',
          defaultValue: true,
          description: 'Muestra botón para quitar la selección (modo field).',
          control: 'boolean',
        },
        {
          name: 'disabled',
          type: 'boolean',
          defaultValue: false,
          description: 'Deshabilita el control.',
          control: 'boolean',
        },
        {
          name: 'error',
          type: 'boolean',
          defaultValue: false,
          description: 'Estado de error visual.',
          control: 'boolean',
        },
        {
          name: 'errorMessage',
          type: 'string',
          defaultValue: undefined,
          description: 'Mensaje de error debajo del campo.',
          control: 'text',
          dependsOn: { prop: 'error', value: true },
        },
        {
          name: 'helperText',
          type: 'string',
          defaultValue: undefined,
          description: 'Texto de ayuda.',
          control: 'text',
        },
      ],
    },
    {
      title: 'Tema',
      props: [
        {
          name: 'theme',
          type: 'FileBoxThemeInput',
          defaultValue: undefined,
          description: 'Preset o tema personalizado (comparte temas de TextBox).',
          control: 'select',
          options: [
            { label: 'Global (inherit)', value: '' },
            { label: 'Dark', value: 'dark' },
            { label: 'Light', value: 'light' },
            { label: 'Modern Dark', value: 'modern-dark' },
            { label: 'Modern Light', value: 'modern-light' },
            { label: 'Enterprise Dark', value: 'enterprise-dark' },
            { label: 'Enterprise Light', value: 'enterprise-light' },
          ],
        },
      ],
    },
  ],
  events: [
    {
      name: 'onChange',
      signature: '(files: File[]) => void',
      description: 'Se dispara al aceptar archivos nuevos o al limpiar la selección.',
      handlerType: 'FileBoxOnChangeHandler',
      payloadType: 'FileBoxChangeValue',
    },
    {
      name: 'onReject',
      signature: '(rejected: FileRejection[]) => void',
      description: 'Se dispara cuando archivos no pasan accept / maxSize / maxFiles.',
      handlerType: 'FileBoxOnRejectHandler',
      payloadType: 'FileRejection[]',
    },
  ],
};
