import type { TextBoxTheme, TextBoxThemePreset } from './TextBox.theme.types';

export const textBoxThemes: Record<TextBoxThemePreset, TextBoxTheme> = {
  "dark": {
    "fontSize": "0.875rem",
    "borderRadius": "0.5rem",
    "transition": "all 0.15s ease",
    "shadow": "0 1px 2px rgba(0, 0, 0, 0.3)",
    "helperTextColor": "#9ca3af",
    "errorTextColor": "#fca5a5",
    "labelColor": "#d1d5db",
    "clearButtonColor": "#6b7280",
    "clearButtonHoverColor": "#9ca3af",
    "variants": {
      "primary": {
        "background": "#1f2937",
        "text": "#e5e7eb",
        "border": "#4b5563",
        "placeholderColor": "#6b7280",
        "iconColor": "#9ca3af",
        "hoverBackground": "#1f2937",
        "hoverBorder": "#7D88AD",
        "focusBackground": "#1f2937",
        "focusBorder": "#7D88AD",
        "focusRing": "rgba(140, 152, 190, 0.4)",
        "disabledBackground": "#111827",
        "disabledText": "#4b5563",
        "disabledBorder": "#374151",
        "errorBorder": "#7A5555",
        "errorFocusRing": "rgba(239, 68, 68, 0.3)"
      },
      "secondary": {
        "background": "#374151",
        "text": "#e5e7eb",
        "border": "#4b5563",
        "placeholderColor": "#6b7280",
        "iconColor": "#9ca3af",
        "hoverBackground": "#374151",
        "hoverBorder": "#7D88AD",
        "focusBackground": "#374151",
        "focusBorder": "#7D88AD",
        "focusRing": "rgba(107, 114, 128, 0.3)",
        "disabledBackground": "#1f2937",
        "disabledText": "#4b5563",
        "disabledBorder": "#374151",
        "errorBorder": "#7A5555",
        "errorFocusRing": "rgba(239, 68, 68, 0.3)"
      },
      "outline": {
        "background": "transparent",
        "text": "#e5e7eb",
        "border": "#4b5563",
        "placeholderColor": "#6b7280",
        "iconColor": "#9ca3af",
        "hoverBackground": "rgba(255, 255, 255, 0.03)",
        "hoverBorder": "#7D88AD",
        "focusBackground": "rgba(255, 255, 255, 0.03)",
        "focusBorder": "#7D88AD",
        "focusRing": "rgba(107, 114, 128, 0.3)",
        "disabledBackground": "transparent",
        "disabledText": "#4b5563",
        "disabledBorder": "#374151",
        "errorBorder": "#7A5555",
        "errorFocusRing": "rgba(239, 68, 68, 0.3)"
      },
      "ghost": {
        "background": "transparent",
        "text": "#e5e7eb",
        "border": "transparent",
        "placeholderColor": "#6b7280",
        "iconColor": "#9ca3af",
        "hoverBackground": "rgba(255, 255, 255, 0.05)",
        "hoverBorder": "transparent",
        "focusBackground": "rgba(255, 255, 255, 0.05)",
        "focusBorder": "transparent",
        "focusRing": "rgba(107, 114, 128, 0.3)",
        "disabledBackground": "transparent",
        "disabledText": "#4b5563",
        "disabledBorder": "transparent",
        "errorBorder": "#7A5555",
        "errorFocusRing": "rgba(239, 68, 68, 0.3)"
      }
    }
  },

  "light": {
    "fontSize": "0.875rem",
    "borderRadius": "0.5rem",
    "transition": "all 0.15s ease",
    "shadow": "0 1px 2px rgba(0, 0, 0, 0.06)",
    "helperTextColor": "#9ca3af",
    "errorTextColor": "#6B4545",
    "labelColor": "#4b5563",
    "clearButtonColor": "#9ca3af",
    "clearButtonHoverColor": "#6b7280",
    "variants": {
      "primary": {
        "background": "#ffffff",
        "text": "#1f2937",
        "border": "#d1d5db",
        "placeholderColor": "#9ca3af",
        "iconColor": "#6b7280",
        "hoverBackground": "#ffffff",
        "hoverBorder": "#7D88AD",
        "focusBackground": "#ffffff",
        "focusBorder": "#7D88AD",
        "focusRing": "rgba(140, 152, 190, 0.4)",
        "disabledBackground": "#f9fafb",
        "disabledText": "#d1d5db",
        "disabledBorder": "#e5e7eb",
        "errorBorder": "#7A5555",
        "errorFocusRing": "rgba(239, 68, 68, 0.25)"
      },
      "secondary": {
        "background": "#f3f4f6",
        "text": "#1f2937",
        "border": "#d1d5db",
        "placeholderColor": "#9ca3af",
        "iconColor": "#6b7280",
        "hoverBackground": "#f3f4f6",
        "hoverBorder": "#9DABCE",
        "focusBackground": "#f3f4f6",
        "focusBorder": "#9DABCE",
        "focusRing": "rgba(156, 163, 175, 0.3)",
        "disabledBackground": "#f9fafb",
        "disabledText": "#d1d5db",
        "disabledBorder": "#e5e7eb",
        "errorBorder": "#E8CACA",
        "errorFocusRing": "rgba(239, 68, 68, 0.25)"
      },
      "outline": {
        "background": "transparent",
        "text": "#374151",
        "border": "#d1d5db",
        "placeholderColor": "#9ca3af",
        "iconColor": "#6b7280",
        "hoverBackground": "rgba(0, 0, 0, 0.02)",
        "hoverBorder": "#9DABCE",
        "focusBackground": "rgba(0, 0, 0, 0.02)",
        "focusBorder": "#9DABCE",
        "focusRing": "rgba(156, 163, 175, 0.3)",
        "disabledBackground": "transparent",
        "disabledText": "#d1d5db",
        "disabledBorder": "#e5e7eb",
        "errorBorder": "#E8CACA",
        "errorFocusRing": "rgba(239, 68, 68, 0.25)"
      },
      "ghost": {
        "background": "transparent",
        "text": "#374151",
        "border": "transparent",
        "placeholderColor": "#9ca3af",
        "iconColor": "#6b7280",
        "hoverBackground": "rgba(0, 0, 0, 0.04)",
        "hoverBorder": "transparent",
        "focusBackground": "rgba(0, 0, 0, 0.04)",
        "focusBorder": "transparent",
        "focusRing": "rgba(156, 163, 175, 0.3)",
        "disabledBackground": "transparent",
        "disabledText": "#d1d5db",
        "disabledBorder": "transparent",
        "errorBorder": "#E8CACA",
        "errorFocusRing": "rgba(239, 68, 68, 0.25)"
      }
    }
  },

  "modern-dark": {
    "fontSize": "0.875rem",
    "borderRadius": "0.5rem",
    "transition": "all 0.15s ease",
    "shadow": "0 1px 2px rgba(0, 0, 0, 0.3)",
    "helperTextColor": "#9ca3af",
    "errorTextColor": "#fca5a5",
    "labelColor": "#d1d5db",
    "clearButtonColor": "#6b7280",
    "clearButtonHoverColor": "#9ca3af",
    "variants": {
      "primary": {
        "background": "#1f2937",
        "text": "#e5e7eb",
        "border": "#4b5563",
        "placeholderColor": "#6b7280",
        "iconColor": "#9ca3af",
        "hoverBackground": "#1f2937",
        "hoverBorder": "#7D88AD",
        "focusBackground": "#1f2937",
        "focusBorder": "#7D88AD",
        "focusRing": "rgba(140, 152, 190, 0.4)",
        "disabledBackground": "#111827",
        "disabledText": "#4b5563",
        "disabledBorder": "#374151",
        "errorBorder": "#7A5555",
        "errorFocusRing": "rgba(239, 68, 68, 0.3)"
      },
      "secondary": {
        "background": "#374151",
        "text": "#e5e7eb",
        "border": "#4b5563",
        "placeholderColor": "#6b7280",
        "iconColor": "#9ca3af",
        "hoverBackground": "#374151",
        "hoverBorder": "#9DABCE",
        "focusBackground": "#374151",
        "focusBorder": "#9DABCE",
        "focusRing": "rgba(107, 114, 128, 0.3)",
        "disabledBackground": "#1f2937",
        "disabledText": "#4b5563",
        "disabledBorder": "#374151",
        "errorBorder": "#E8CACA",
        "errorFocusRing": "rgba(239, 68, 68, 0.3)"
      },
      "outline": {
        "background": "transparent",
        "text": "#e5e7eb",
        "border": "#4b5563",
        "placeholderColor": "#6b7280",
        "iconColor": "#9ca3af",
        "hoverBackground": "rgba(255, 255, 255, 0.03)",
        "hoverBorder": "#9DABCE",
        "focusBackground": "rgba(255, 255, 255, 0.03)",
        "focusBorder": "#9DABCE",
        "focusRing": "rgba(107, 114, 128, 0.3)",
        "disabledBackground": "transparent",
        "disabledText": "#4b5563",
        "disabledBorder": "#374151",
        "errorBorder": "#E8CACA",
        "errorFocusRing": "rgba(239, 68, 68, 0.3)"
      },
      "ghost": {
        "background": "transparent",
        "text": "#e5e7eb",
        "border": "transparent",
        "placeholderColor": "#6b7280",
        "iconColor": "#9ca3af",
        "hoverBackground": "rgba(255, 255, 255, 0.05)",
        "hoverBorder": "transparent",
        "focusBackground": "rgba(255, 255, 255, 0.05)",
        "focusBorder": "transparent",
        "focusRing": "rgba(107, 114, 128, 0.3)",
        "disabledBackground": "transparent",
        "disabledText": "#4b5563",
        "disabledBorder": "transparent",
        "errorBorder": "#E8CACA",
        "errorFocusRing": "rgba(239, 68, 68, 0.3)"
      }
    }
  },

  "modern-light": {
    "fontSize": "0.875rem",
    "borderRadius": "0.5rem",
    "transition": "all 0.15s ease",
    "shadow": "0 1px 2px rgba(0, 0, 0, 0.06)",
    "helperTextColor": "#9ca3af",
    "errorTextColor": "#b85555",
    "labelColor": "#4b5563",
    "clearButtonColor": "#9ca3af",
    "clearButtonHoverColor": "#6b7280",
    "variants": {
      "primary": {
        "background": "#ffffff",
        "text": "#1f2937",
        "border": "#d1d5db",
        "placeholderColor": "#9ca3af",
        "iconColor": "#6b7280",
        "hoverBackground": "#ffffff",
        "hoverBorder": "#9DABCE",
        "focusBackground": "#ffffff",
        "focusBorder": "#9DABCE",
        "focusRing": "rgba(120, 135, 175, 0.35)",
        "disabledBackground": "#f9fafb",
        "disabledText": "#d1d5db",
        "disabledBorder": "#e5e7eb",
        "errorBorder": "#E8CACA",
        "errorFocusRing": "rgba(239, 68, 68, 0.25)"
      },
      "secondary": {
        "background": "#f3f4f6",
        "text": "#1f2937",
        "border": "#d1d5db",
        "placeholderColor": "#9ca3af",
        "iconColor": "#6b7280",
        "hoverBackground": "#f3f4f6",
        "hoverBorder": "#9DABCE",
        "focusBackground": "#f3f4f6",
        "focusBorder": "#9DABCE",
        "focusRing": "rgba(156, 163, 175, 0.3)",
        "disabledBackground": "#f9fafb",
        "disabledText": "#d1d5db",
        "disabledBorder": "#e5e7eb",
        "errorBorder": "#E8CACA",
        "errorFocusRing": "rgba(239, 68, 68, 0.25)"
      },
      "outline": {
        "background": "transparent",
        "text": "#374151",
        "border": "#d1d5db",
        "placeholderColor": "#9ca3af",
        "iconColor": "#6b7280",
        "hoverBackground": "rgba(0, 0, 0, 0.02)",
        "hoverBorder": "#9DABCE",
        "focusBackground": "rgba(0, 0, 0, 0.02)",
        "focusBorder": "#9DABCE",
        "focusRing": "rgba(156, 163, 175, 0.3)",
        "disabledBackground": "transparent",
        "disabledText": "#d1d5db",
        "disabledBorder": "#e5e7eb",
        "errorBorder": "#E8CACA",
        "errorFocusRing": "rgba(239, 68, 68, 0.25)"
      },
      "ghost": {
        "background": "transparent",
        "text": "#374151",
        "border": "transparent",
        "placeholderColor": "#9ca3af",
        "iconColor": "#6b7280",
        "hoverBackground": "rgba(0, 0, 0, 0.04)",
        "hoverBorder": "transparent",
        "focusBackground": "rgba(0, 0, 0, 0.04)",
        "focusBorder": "transparent",
        "focusRing": "rgba(156, 163, 175, 0.3)",
        "disabledBackground": "transparent",
        "disabledText": "#d1d5db",
        "disabledBorder": "transparent",
        "errorBorder": "#E8CACA",
        "errorFocusRing": "rgba(239, 68, 68, 0.25)"
      }
    }
  },

  "enterprise-dark": {
    "fontSize": "0.875rem",
    "borderRadius": "0.5rem",
    "transition": "all 0.15s ease",
    "shadow": "0 1px 2px rgba(0, 0, 0, 0.3)",
    "helperTextColor": "#9ca3af",
    "errorTextColor": "#fca5a5",
    "labelColor": "#d1d5db",
    "clearButtonColor": "#6b7280",
    "clearButtonHoverColor": "#9ca3af",
    "variants": {
      "primary": {
        "background": "#1f2937",
        "text": "#e5e7eb",
        "border": "#4b5563",
        "placeholderColor": "#6b7280",
        "iconColor": "#9ca3af",
        "hoverBackground": "#1f2937",
        "hoverBorder": "#7D88AD",
        "focusBackground": "#1f2937",
        "focusBorder": "#7D88AD",
        "focusRing": "rgba(140, 152, 190, 0.4)",
        "disabledBackground": "#111827",
        "disabledText": "#4b5563",
        "disabledBorder": "#374151",
        "errorBorder": "#7A5555",
        "errorFocusRing": "rgba(239, 68, 68, 0.3)"
      },
      "secondary": {
        "background": "#374151",
        "text": "#e5e7eb",
        "border": "#4b5563",
        "placeholderColor": "#6b7280",
        "iconColor": "#9ca3af",
        "hoverBackground": "#374151",
        "hoverBorder": "#9DABCE",
        "focusBackground": "#374151",
        "focusBorder": "#9DABCE",
        "focusRing": "rgba(107, 114, 128, 0.3)",
        "disabledBackground": "#1f2937",
        "disabledText": "#4b5563",
        "disabledBorder": "#374151",
        "errorBorder": "#E8CACA",
        "errorFocusRing": "rgba(239, 68, 68, 0.3)"
      },
      "outline": {
        "background": "transparent",
        "text": "#e5e7eb",
        "border": "#4b5563",
        "placeholderColor": "#6b7280",
        "iconColor": "#9ca3af",
        "hoverBackground": "rgba(255, 255, 255, 0.03)",
        "hoverBorder": "#9DABCE",
        "focusBackground": "rgba(255, 255, 255, 0.03)",
        "focusBorder": "#9DABCE",
        "focusRing": "rgba(107, 114, 128, 0.3)",
        "disabledBackground": "transparent",
        "disabledText": "#4b5563",
        "disabledBorder": "#374151",
        "errorBorder": "#E8CACA",
        "errorFocusRing": "rgba(239, 68, 68, 0.3)"
      },
      "ghost": {
        "background": "transparent",
        "text": "#e5e7eb",
        "border": "transparent",
        "placeholderColor": "#6b7280",
        "iconColor": "#9ca3af",
        "hoverBackground": "rgba(255, 255, 255, 0.05)",
        "hoverBorder": "transparent",
        "focusBackground": "rgba(255, 255, 255, 0.05)",
        "focusBorder": "transparent",
        "focusRing": "rgba(107, 114, 128, 0.3)",
        "disabledBackground": "transparent",
        "disabledText": "#4b5563",
        "disabledBorder": "transparent",
        "errorBorder": "#E8CACA",
        "errorFocusRing": "rgba(239, 68, 68, 0.3)"
      }
    }
  },

  "enterprise-light": {
    "fontSize": "0.875rem",
    "borderRadius": "0.5rem",
    "transition": "all 0.15s ease",
    "shadow": "0 1px 2px rgba(0, 0, 0, 0.06)",
    "helperTextColor": "#9ca3af",
    "errorTextColor": "#b85555",
    "labelColor": "#4b5563",
    "clearButtonColor": "#9ca3af",
    "clearButtonHoverColor": "#6b7280",
    "variants": {
      "primary": {
        "background": "#ffffff",
        "text": "#1f2937",
        "border": "#d1d5db",
        "placeholderColor": "#9ca3af",
        "iconColor": "#6b7280",
        "hoverBackground": "#ffffff",
        "hoverBorder": "#9DABCE",
        "focusBackground": "#ffffff",
        "focusBorder": "#9DABCE",
        "focusRing": "rgba(120, 135, 175, 0.35)",
        "disabledBackground": "#f9fafb",
        "disabledText": "#d1d5db",
        "disabledBorder": "#e5e7eb",
        "errorBorder": "#E8CACA",
        "errorFocusRing": "rgba(239, 68, 68, 0.25)"
      },
      "secondary": {
        "background": "#f3f4f6",
        "text": "#1f2937",
        "border": "#d1d5db",
        "placeholderColor": "#9ca3af",
        "iconColor": "#6b7280",
        "hoverBackground": "#f3f4f6",
        "hoverBorder": "#9DABCE",
        "focusBackground": "#f3f4f6",
        "focusBorder": "#9DABCE",
        "focusRing": "rgba(156, 163, 175, 0.3)",
        "disabledBackground": "#f9fafb",
        "disabledText": "#d1d5db",
        "disabledBorder": "#e5e7eb",
        "errorBorder": "#E8CACA",
        "errorFocusRing": "rgba(239, 68, 68, 0.25)"
      },
      "outline": {
        "background": "transparent",
        "text": "#374151",
        "border": "#d1d5db",
        "placeholderColor": "#9ca3af",
        "iconColor": "#6b7280",
        "hoverBackground": "rgba(0, 0, 0, 0.02)",
        "hoverBorder": "#9DABCE",
        "focusBackground": "rgba(0, 0, 0, 0.02)",
        "focusBorder": "#9DABCE",
        "focusRing": "rgba(156, 163, 175, 0.3)",
        "disabledBackground": "transparent",
        "disabledText": "#d1d5db",
        "disabledBorder": "#e5e7eb",
        "errorBorder": "#E8CACA",
        "errorFocusRing": "rgba(239, 68, 68, 0.25)"
      },
      "ghost": {
        "background": "transparent",
        "text": "#374151",
        "border": "transparent",
        "placeholderColor": "#9ca3af",
        "iconColor": "#6b7280",
        "hoverBackground": "rgba(0, 0, 0, 0.04)",
        "hoverBorder": "transparent",
        "focusBackground": "rgba(0, 0, 0, 0.04)",
        "focusBorder": "transparent",
        "focusRing": "rgba(156, 163, 175, 0.3)",
        "disabledBackground": "transparent",
        "disabledText": "#d1d5db",
        "disabledBorder": "transparent",
        "errorBorder": "#E8CACA",
        "errorFocusRing": "rgba(239, 68, 68, 0.25)"
      }
    }
  },

};
